import Head from "next/head";
import Link from "next/link";
export default function Home() {
  return (
    <div >
      <Head> 
        <title>Hola mundo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <h1>Hola</h1>
      <Link href="/timeline">Go to timeline</Link>
     <style jsx>{`
        h1 {
          color: red;
        }
      `}
      </style>
    </div>
  );
}