import Head from 'next/head'
import {normalStyle, globalStyles } from './styles'
import { breakpoints } from '../../styles/theme'
export default function AppLayout({children}) {
  return (
    <>
        <Head> 
        <title>Hola mundo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <main>
        
          {children}
        </main>
      </div>

      <style jsx global>{globalStyles}</style>
      <style jsx>{normalStyle}</style>
    </>
  )
}
